// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAtfRj5TawqRRumtwz5Wq_Mpy8REflTh0',
    appId: '1:707581174284:web:46c9ceca26c083e5c60429',
    messagingSenderId: '707581174284',
    projectId: 'fyp-project-c2e79',
    authDomain: 'fyp-project-c2e79.firebaseapp.com',
    storageBucket: 'fyp-project-c2e79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3960yGMEHBrwHQIJjeOm8j6wiGxwE_u8',
    appId: '1:707581174284:android:2229f3897da2e98ac60429',
    messagingSenderId: '707581174284',
    projectId: 'fyp-project-c2e79',
    storageBucket: 'fyp-project-c2e79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_nTwjNjV7KiNWTdoYkheYyrI0Dkyydm0',
    appId: '1:707581174284:ios:09f061d2a224cd1bc60429',
    messagingSenderId: '707581174284',
    projectId: 'fyp-project-c2e79',
    storageBucket: 'fyp-project-c2e79.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );
}
